name: test_work_flow_label

on:
  label:
    types: [created, edited, deleted, iwasawa]

jobs:
    echo_sample:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.7
              uses: actions/setup-python@v2
              with:
                python-version: "3.7"
            - name: echo_text
              run: |
                echo "this is a test about GitHub Actions works or not."